### ISSUE TITLE
cannot use path@version syntax in GOPATH mode

### ISSUE THREAD

**Issue by Billybangleballs** [kelvie/gbmonctl#12]
I installed this last year on a raspberry pi, it worked fine.
This year the command "`go install github.com/kelvie/gbmonctl@latest`", no longer works, I followed the same procedure as last year, as I documented it at the time for future use.
The error message,"`can't load package: package github.com/kelvie/gbmonctl@latest: cannot use path@version syntax in GOPATH mode`", doesn't help me at all.
I'm not an expert at go, or anything else for that matter, but I'm reasonable at following instructions. Something has changed, but that something has not propagated through to the installation instructions.

Please help.

**Comment by kelvie** [comment]
https://github.com/kubernetes/client-go/blob/master/INSTALL.md#go-modules-disabled

Found this via web search

**Comment by Billybangleballs** [comment]
Thanks. I managed to install it, but it was not as easy as it was last year. ;)

It works with a M34WQ btw. I used wireshark to see what the Gigabyte software was saying, and added the bits I needed to switch the hdmi and dp inputs from cli.

Thank you for sharing your work.
